- name: ansible playbook for frontend
  hosts: frontend
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: enable the service    
      ansible.builtin.service:
        name: nginx
        enabled: yes

    - name: starting the service    
      ansible.builtin.service:
        name: nginx
        state: started
